sudo: required

language: java

jdk:
  - oraclejdk9

python: 2.7

install:
  - sudo apt-get install -y python-tk
  - sudo pip     install --upgrade pip
  - sudo pip     install -r requirements.txt

script:
  - cd src/test/python/
  - python functions.py
#  - ./gradlew test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

